import { prisma } from "@/lib/db";
import { notFound } from "next/navigation";
import ShareClient from "./ShareClient";
import { Metadata } from "next";

export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> {
  const { id } = await params;
  const resume = await prisma.resumeHistory.findUnique({
    where: { id }
  });

  if (!resume) {
    return { title: "Timeline Not Found | VerseCV" };
  }

  const name = (resume.transformedData as any)?.personal_info?.name || (resume.transformedData as any)?.name || "Professional";
  return {
    title: `${name}'s ${resume.universe} Timeline | VerseCV`,
    description: `View this alternate reality resume generated by VerseCV in the ${resume.universe} universe.`
  };
}

export default async function SharedResumePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const resume = await prisma.resumeHistory.findUnique({
    where: { id }
  });

  if (!resume) {
    notFound();
  }

  return (
    <ShareClient 
      data={resume.transformedData as any} 
      universeName={resume.universe} 
    />
  );
}
